
on papi placeholder request with the prefix "LeafBedWars":
	loop "kills", "deaths", "broken-beds", "wins", "final-kills", "coins", "level", "xp-need" and "xp":	
		identifier is "%loop-value-1%"
		if {-bw::player::stats::%player%::%loop-value-1%} is set:
			set the result to "%{-bw::player::stats::%player%::%loop-value-1%}%"
		else:
			set the result to "0"

on load:
	broadcast "%yaml value ""Messages.Prefix"" from ""bw.language""%&aPlaceholderAPI module loaded."



